# Generated by Django 4.1.6 on 2023-04-15 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicutils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='album',
            name='pab_date',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicutils.user', verbose_name='Альбом'),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.TimeField(verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='track',
            name='singer',
            field=models.CharField(max_length=250, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=250, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=250, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='playlist_size',
            field=models.IntegerField(verbose_name='Размер плей-листа'),
        ),
        migrations.AlterField(
            model_name='userplaylist',
            name='track_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicutils.track', verbose_name='Трек'),
        ),
        migrations.AlterField(
            model_name='userplaylist',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicutils.user', verbose_name='Пользователь'),
        ),
    ]
