# Generated by Django 4.1.6 on 2023-04-15 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicutils', '0002_alter_album_description_alter_album_pab_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name': 'Треки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userplaylist',
            options={'verbose_name': 'Плей-листы пользователей'},
        ),
        migrations.AlterField(
            model_name='track',
            name='album_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicutils.album', verbose_name='Альбом'),
        ),
    ]
