# Generated by Django 4.1.6 on 2023-04-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicutils', '0003_alter_album_options_alter_track_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='album_id',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='userplaylist',
            old_name='track_id',
            new_name='track',
        ),
        migrations.RenameField(
            model_name='userplaylist',
            old_name='user_id',
            new_name='user',
        ),
    ]
