# Generated by Django 4.1.6 on 2023-04-25 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('slogan', models.CharField(max_length=350, verbose_name='Слоган')),
            ],
            options={
                'verbose_name': 'Программное обеспечение',
                'verbose_name_plural': 'Порграммные обеспечения',
            },
        ),
        migrations.CreateModel(
            name='SoftwareCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft.company', verbose_name='Компания')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft.software', verbose_name='Программное обеспечени')),
            ],
            options={
                'verbose_name': 'ПО - Компания',
                'verbose_name_plural': 'ПО - Компании',
            },
        ),
    ]
