# Generated by Django 4.1.6 on 2023-04-25 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='price',
            field=models.IntegerField(default=123, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='softwarecompany',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft.software', verbose_name='Программное обеспечение'),
        ),
    ]
