# Generated by Django 4.1.6 on 2023-04-25 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=250, verbose_name='Производитель')),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Электроника',
                'verbose_name_plural': 'Электроника',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=250, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technic.electronic', verbose_name='Электроника')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technic.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'ПО - Компания',
                'verbose_name_plural': 'ПО - Компании',
            },
        ),
    ]
